############################
# Setup database container #
############################
version: "3.8"
services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=tripjudge
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
