############################
# Setup database container #
############################
version: "3.8"
services:
  web:
    build: .
    ports:
     - 3000:3000
    depends_on:
      - db
    environment:
      - DATA_HOST=postgres
      - DATA_PORT=5432
      - DATE_USERNAME=admin
      - DATA_PASSWORD=admin
      - DATA_DATABASE=tripjudge
    links:
      - postgres:db.example.com
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=tripjudge
