############################
# Setup database container #
############################
version: "3.8"
services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - 5050:80
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=tripjudge
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - db_network

  pgadmin:
    image: dpage/pgadmin4:4.19
    restart: always
    ports:
      - 8001:8080/tcp
    environment:
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=8080
      - PGADMIN_DEFAULT_EMAIL=admin@admin.nl
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
